### ISSUE TITLE
Using Path.join with a trailing slash causes error

### ISSUE THREAD

**Issue by k00k** [hapipip/pellmell#1]
First, thanks for this module, it's extremely clean and useful!

When using `Path.join` on a directory, if the directory string contains a trailing slash, Pellmell throws an error. I haven't had a chance to dive into Pellmell's source to see why, but here's the details:

The following configuration doesn't work:

```
const configFiles = [
  Path.join(__dirname, '/config/defaults.js'), // default values
  Path.join(__dirname, '/config/services/') // all service configs - db, etc
]
const conf = Pellmell.patch(configFiles)
```

It results in an error: `Error: Invalid defaults value: must be an object`

When I remove the trailing slash from `/config/services/` it works.

The following works perfectly:

```
const configFiles = [
  Path.join(__dirname, '/config/defaults.js'), // default values
  Path.join(__dirname, '/config/services') // all service configs - db, etc
]
const conf = Pellmell.patch(configFiles)
```

If we don't use Path.join, it works just fine as well (with or without trailing slash):
```
const configFiles = [
  Path.join(__dirname, '/config/defaults.js'), // default values
  './config/services/', // all service configs - db, etc
]
const conf = Pellmell.patch(configFiles)
```

**Comment by ndious** [comment]
Thanks for the issue. I will watching that soon.
