### ISSUE TITLE
Pellmell should always return an object, even if no file was found?

### ISSUE THREAD

**Issue by Gastonite** [hapipip/pellmell#3]

**Comment by ndious** [comment]
This is a pretty good answer.

If we do that, we didn't have visual errors when loading fail. But this is not breaking the process.

One solution can be to use a callback function. Like this:

``` js
Pellmell.patch(['file/path'], {}, (err, res) => {
  if (err) {
    // do what you want
  }

  // even if there is an error you can use the result
});
```

Or we use a promise:

``` js
const configure = (data) => {
  // do what you need with your data
}

Pellmell.patch(['file/path'], {}).then(configure, (data) => {
  console.log(data.errors);
  configure(data);
});
```

But if we do that, we need to create a method patchSync I think.

**Comment by Gastonite** [comment]
I think it is the responsibility of the user to ensure that the paths it provides exist.

**Comment by ndious** [comment]
But in case of a typo or additional issue not detected, get errors can save time for the developer and us.
In all cases, we need error reporting, but this errors can be non blocking.

**Comment by Gastonite** [comment]
+1 for non blocking errors =)
